version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: kashuta/backend:dev
    depends_on:
      - db
    ports:
      - "5001:3001"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_DIALECT: ${POSTGRES_DIALECT}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: kashuta/frontend:dev
    ports:
      - "5002:3000"

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_DIALECT: ${POSTGRES_DIALECT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
