version: '3.9'

services:
  backend:
    build: ./backend
    image: kashuta/backend:0.1
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db

  frontend:
    build: ./frontend
    image: kashuta/frontend:0.1
    volumes:
      - ./frontend:/app/frontend

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
