const errorStatus = [
  'INVALID_CREDENTIALS',
  'USER_NOT_FOUND',
  'USER_ALREADY_EXISTS',
  'INVALID_TOKEN',
  'TOKEN_EXPIRED',
  'INVALID_REFRESH_TOKEN',
  'INVALID_EMAIL',
  'INVALID_PASSWORD',
  'INVALID_USERNAME',
  'VALIDATION_ERROR',
];

export default errorStatus;
