openapi: 3.0.0
paths:
  /registration:
    post:
      summary: Register a new user
      description: Create a new user account with the provided email, username, and password
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userName:
                  type: string
                  description: The desired user name for the new user account
                email:
                  type: string
                  description: The email address for the new user account
                  format: email
                password:
                  type: string
                  description: The password for the new user account
              required:
                - userName
                - email
                - password
      responses:
        200:
          description: User registration successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: Access token for the new user
                  refreshToken:
                    type: string
                    description: Refresh token for the new user
                  user:
                    type: object
                    properties:
                      userName:
                        type: string
                        description: The user name of the new user
                      uniqueString:
                        type: string
                        description: A unique identifier string for the new user
        422:
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    oneOf:
                      - example: Invalid username
                      - example: Invalid email
                      - example: Invalid password

  /login:
    post:
      summary: Log in a user
      description: Log in a user with the provided email and password
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: The email address of the user
                  format: email
                password:
                  type: string
                  description: The password for the user's account
              required:
                - email
                - password
      responses:
        200:
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: Access token for the logged-in user
                  refreshToken:
                    type: string
                    description: Refresh token for the logged-in user
                  userFront:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: The user ID
                      userName:
                        type: string
                        description: The user name of the logged-in user
                      email:
                        type: string
                        format: email
                        description: The email address of the logged-in user
                      role:
                        type: string
                        description: The role of the logged-in user
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    oneOf:
                      - example: User not found
                      - example: User not activated, please check your email
                      - example: Invalid password
        422:
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    oneOf:
                      - example: Invalid email
                      - example: Invalid password
