name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          dockerfile: ./backend/Dockerfile
          push: true
          tags: kashuta/backend:0.1
      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          dockerfile: ./frontend/Dockerfile
          push: true
          tags: kashuta/frontend:0.1

  deploy:
    runs-on: ubuntu-latest
    needs: build-push

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install SSH Client and sshpass
        run: sudo apt-get install -y ssh-client sshpass

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa

      - name: Copy files to remote server
        run: |
          sshpass -p "${{ secrets.SSH_KEY_PASSWORD }}" ssh -o StrictHostKeyChecking=no -i id_rsa -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_HOST }} "echo 'SSH connection test successful'"
          sshpass -p "${{ secrets.SSH_KEY_PASSWORD }}" scp -v -o StrictHostKeyChecking=no -i id_rsa -r -P ${{ secrets.SSH_PORT }} docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_HOST }}:/var/www/qarapidreports

      - name: Deploy to remote server
        run: |
          sshpass -p "${{ secrets.SSH_KEY_PASSWORD }}" ssh -v -o StrictHostKeyChecking=no -i id_rsa -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_HOST }} "cd /var/www/qarapidreports && docker-compose pull && docker-compose down && docker-compose up -d"
