name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Log in to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: kashuta/backend:0.1
      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: kashuta/frontend:0.1

  deploy:
    runs-on: ubuntu-latest
    needs: build-push

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install SSH Client and sshpass
        run: sudo apt-get install -y ssh-client sshpass

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa_no_passphrase
          chmod 600 id_rsa_no_passphrase

      - name: Add remote server to known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DROPLET_HOST }} $(ssh-keyscan -H ${{ secrets.DROPLET_HOST }})" >> ~/.ssh/known_hosts

      - name: Copy files to remote server
        run: |
          scp -i id_rsa_no_passphrase -r -P ${{ secrets.SSH_PORT }} docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_HOST }}:/var/www/qarapidreports

      - name: Deploy to remote server
        run: |
          ssh -i id_rsa_no_passphrase -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_HOST }} "cd /var/www/qarapidreports && docker-compose pull && docker-compose down && docker-compose up -d"
